### ISSUE TITLE
Styling individual words

### ISSUE THREAD

**Issue by kiviaj** [arve0/markdown-it-attrs#102]
Markdown-it-attrs is very handy, thumbs ub. I'm wondering if the use case below is currently supported with an option maybe (I couldn't find it yet), or if there is any reason for not supporting it?

Example input:
```md
paragraph style me{.red} more text
```

Current output:
```html
<p>paragraph style me{.red} more text</p>
```

Expected output:
```html
<p>paragraph style <span class="red">me</span> more text</p>
```
Cheers

**Comment by arve0** [comment]
See https://github.com/arve0/markdown-it-attrs/issues/38.

**Comment by kiviaj** [comment]
Thanks a lot arve0, markdown-it-bracketed-spans seems to work great in combination with markdown-it-attrs indeed. Mentioning the combination of both in the readme could be helpful to others in my humble opinion.

**Comment by arve0** [comment]
Glad it worked for you. If the readme is not up to your standard, send a suggestion as a pull request 🙂

**Comment by kiviaj** [comment]
:-)
