### ISSUE TITLE
Cannot read property 'attrPush' of undefined

### ISSUE THREAD

**Issue by douyacun** [arve0/markdown-it-attrs#104]
react 16.0
Example input:
```md
md.use(markdownItAttrs, {
        // optional, these are default options
        leftDelimiter: '{',
        rightDelimiter: '}',
        allowedAttributes: []  // empty array = all attributes are allowed
})

[HD中字](){data-toggle=modal}
```

Current output:
```html
TypeError: Cannot read property 'attrPush' of undefined
exports.addAttrs
/Documents/github.com/www.douyacun.com/node_modules/markdown-it-attrs/utils.js:127:13
transform
/Documents/github.com/www.douyacun.com/node_modules/markdown-it-attrs/patterns.js:131:15
Array.curlyAttrs
/Documents/github.com/www.douyacun.com/node_modules/markdown-it-attrs/index.js:30:19
Core.process
/Documents/github.com/www.douyacun.com/node_modules/markdown-it/lib/parser_core.js:51:13
MarkdownIt.parse
/Documents/github.com/www.douyacun.com/node_modules/markdown-it/lib/index.js:523:13
MarkdownIt.render
/Documents/github.com/www.douyacun.com/node_modules/markdown-it/lib/index.js:543:36
```

Expected output:
```html
<a data-toggle="modal">HD中字</a>
```

**Comment by arve0** [comment]
Hi, thank you for reporting. Which version of markdown-it and markdown-it-attrs are you using?

**Comment by Kidounet** [comment]
Hi,

Same issue here.

To reproduce, just try this :
simple _texte_{.class} with class

Installed package :
"dependencies": {
    "@nuxtjs/markdownit": "^1.2.9",
    "markdown-it-abbr": "^1.0.4",
    "markdown-it-attrs": "^3.0.2",
    "markdown-it-footnote": "^3.0.2",
    "markdown-it-sub": "^1.0.0",
    "markdown-it-sup": "^1.0.0",
    "markdown-it-underline": "^1.0.1",
}

In package-lock.json : installed version of markdown-it is 8.4.2


Just force install of last version by adding last version of Markdown-it in package.json :
"dependencies": {
    "@nuxtjs/markdownit": "^1.2.9",
    "markdown-it": "^10.0.0",
    "markdown-it-abbr": "^1.0.4",
    "markdown-it-attrs": "^3.0.2",
    "markdown-it-footnote": "^3.0.2",
    "markdown-it-sub": "^1.0.0",
    "markdown-it-sup": "^1.0.0",
    "markdown-it-underline": "^1.0.1",
}

And now all working well

Thanks for this extension, i use it for add color in markdown.
have fun !

**Comment by awmartin** [comment]
I still get this error with the same versions of @nuxt/markdownit, markdown-it, and markdown-it-attrs. I have no other dependencies. With the following:

    [Example](https://example.com){target=_blank}

**Comment by arve0** [comment]
@awmartin Hi👋 What versions do you have installed? `npm ls markdown-it` and `npm ls markdown-it-attrs`.

**Comment by dmnsgn** [comment]
This issue might be related: https://github.com/arve0/markdown-it-attrs/issues/107
```json
"markdown-it": "^11.0.0",
"markdown-it-attrs": "^3.0.2",
```
