### ISSUE TITLE
Nuxt application dies when using markdown-it-attrs in IE11 - is there a polyfill?

### ISSUE THREAD

**Issue by philjclarke** [arve0/markdown-it-attrs#106]
We have a Frontend App developed using Nuxt connecting to a Strapi.io CMS at the backend, which supports Markdown.

Everything works as expected on most browsers, but we have a specific issue with IE11, where, if we include the markdown-it-attrs plugin we see arrow function issues that cause a syntax error, and stop any functionality working (even simple JS events). Removing the plugin resolves the issue, but then we lose our attributes on our Markdown text.

We've tried removing other dependencies, and testing between dev and production, but still see the issue, so I'm assuming it's not a clash with other packages. 

Relevant code from nuxt.config.js is:

**modules: [
    '@nuxtjs/axios',
    '@nuxtjs/auth',
    'nuxt-polyfill',
    '@nuxtjs/markdownit'
  ],
  markdownit: {
    preset: 'default',
    injected: true,
    use: [
      'markdown-it-attrs'
    ]
  },**

and

**build: {
    transpile: [
      "@nuxtjs/markdownit"
    ],
},**

The packages we are using are:

**"dependencies": {
    "@babel/core": "^7.1.2",
    "@babel/plugin-transform-arrow-functions": "^7.8.3",
    "@babel/polyfill": "^7.8.7",
    "@babel/preset-env": "^7.1.0",
    "@nuxt/babel-preset-app": "^2.12.2",
    "@nuxtjs/auth": "^4.9.1",
    "@nuxtjs/axios": "^5.10.1",
    "@nuxtjs/bulma": "^1.2.7",
    "@nuxtjs/markdownit": "^1.2.9",
    "markdown-it-attrs": "^3.0.2",
    "array.prototype.flat": "^1.2.3",
    "bulma-checkradio": "^1.1.1",
    "bulma-tooltip": "^3.0.2",
    "core-js": "^2.6.11",
    "event-source-polyfill": "^1.0.12",
    "nuxt": "^2.12.1",
    "nuxt-polyfill": "^1.0.3",
    "promise-polyfill": "^8.1.3",
    "url-polyfill": "^1.1.8",
    "v-click-outside": "^3.0.1"
  },
  "devDependencies": {
    "@fortawesome/fontawesome-free": "^5.12.1",
    "@nuxtjs/eslint-config": "^1.1.2",
    "@nuxtjs/eslint-module": "^1.2.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.8.0",
    "eslint-plugin-nuxt": "^0.5.1",
    "node-sass": "^4.14.0",
    "sass-loader": "^8.0.2"
  },**

Has any one seen/resolved this issue, or is there a polyfill we can use?

**Comment by arve0** [comment]
Hi, thanks for reporting👍 Have you tried the browser build? https://github.com/arve0/markdown-it-attrs/blob/master/markdown-it-attrs.browser.js

The browser setup probably needs some update to support IE out of the box.

**Comment by philjclarke** [comment]
Hi, thanks for speedy reply @arve0! No, haven't tried this - will give it a go - thanks!
