### ISSUE TITLE
Attributes to inline link not added when html:true and custom delimiters

### ISSUE THREAD

**Issue by dmnsgn** [arve0/markdown-it-attrs#107]
I am using custom delimiters in the form of html comments to hide attributes from normal markdown:

```js
md.use(markdownItAttrs, {
  leftDelimiter: "<!--attrs ",
  rightDelimiter: "-->"
});
```

I also init with html true as I need this feature: `const md = markdownIt({ html: true });`

This generates two issues:
- attributes are not added to generated <a> tag if it has content following the link
- attributes are added to the parent <p> tag if there is no content following the link
 
See js fiddle or below: https://jsfiddle.net/dmnsgn/4co5zbLe/12/

Example input:
```md
Inline link doesn't process attributes [website](http://website.com)<!--attrs target=_blank .green --> with content after link.

Inline paragraph with no content after link put attributes on paragraph [website](http://website.com)<!--attrs target=_blank .green -->
```

Current output:
```html
// Comment is unchanged here
<p>Inline link doesn't process attributes <a href="http://website.com">website</a>
<!--attrs target=_blank .green --> with content after link.</p>

// P gets the attributes
<p target="_blank" class="green">Inline paragraph with no content after link put attributes on paragraph <a href="http://website.com">website</a>
</p>
```

Expected output:
```html
<p>Inline link doesn't process attributes <a href="http://website.com" target="_blank" class="green">website</a> with content after link.</p>
```

To note: with html: false, I get the expected output.

```
└── markdown-it-attrs@3.0.2 
└── markdown-it@11.0.0 
```

**Comment by arve0** [comment]
Thanks for reporting 👍 I'll close this issue, as it's out of scope for the project. Feel free to fork or send pull requests if you want to implement `<!-- -->` style delimiters.
