### ISSUE TITLE
Propagation of Attributes in Markdown-it-container

### ISSUE THREAD

**Issue by StefanZander** [arve0/markdown-it-attrs#111]
I am using both extensions `markdown-it-attrs`  and `markdown-it-container` in conjunction with Marp in order to create and render my lecture slides using markdown. 

When combining both extensions, e.g.,

```
::: definition
some def text...

Source: some source text {.source}
:::
```

the `.source` class will be propagated to the definition container (the parent div) rather than to the paragraph that represents the source text.

The problem as described in Post 1 in Issue #72 is still present to me. 

I also tried the workaround proposed by @mb21 in Issue #72 but it does not work in my setup.

Since I really like both extensions, I hope there is another way of making both work together.

Thanks in advance.

**Comment by arve0** [comment]
Hi! I'm sorry, but I do not have time to debug your bug. If you find out that the error is on markdown-it-attrs, I would be glad to get an update.

**Comment by oncletom** [comment]
I opened a pull request with a failing test case.

I have not figured out yet if it's a bug, or a missing feature.

What's tough thoug, is this syntax is added via an additional plugin, it's not part of `markdown-it` core 😶‍🌫️

**Comment by arve0** [comment]
Hi 🙂 Sorry to inform that I do not have time to investigate this issue. Feel free to reopen issue if you want to take a stab yourself.
