### ISSUE TITLE
Does the class support regular expression filtering

### ISSUE THREAD

**Issue by zhangyul** [arve0/markdown-it-attrs#112]
```js
md.use(markdownItAttrs, {
    allowedAttributes: [/^\.markdown-.*$/] // empty array = all attributes are allowed
 });
```

Example input:

```md
test{.red .markdown-red}
```

Current output:

```html
<p>test</p>
```

Expected output:

```html
<p class="markdown-red">test</p>
```

**Comment by arve0** [comment]
> Does the class support regular expression filtering

No not currently. `allowedAttributes` only scans attribute keys, not values of attributes.

**Comment by arve0** [comment]
Hi 🙂 I'll close this issue as out of scope, as I do not have time to implement it. Of anyone wants to implement, feel free to reopen.
