### ISSUE TITLE
Tables break in markdown-it v12

### ISSUE THREAD

**Issue by valtlai** [arve0/markdown-it-attrs#113]
Markdown-it v12 was just [released](https://github.com/markdown-it/markdown-it/blob/master/CHANGELOG.md#1200---2020-10-14). We can’t just bump the markdown-it version because tables don’t work correctly without code changes. I’m not sure if markdown-it-attrs or markdown-it itself should be updated to fix the issue.

Markdown-it versions:
12.0.0

```bash
├── UNMET PEER DEPENDENCY markdown-it@12.0.0
└── markdown-it-attrs@3.0.3
```

Example input:

```md
| Foo   | Baz   |
| ----- | ----- |
| sin   | cos   |
{.lorem}
```

Current output:

```html
<table>
<thead>
<tr>
<th>Foo</th>
<th>Baz</th>
</tr>
</thead>
<tbody>
<tr>
<td>sin</td>
<td>cos</td>
</tr>
<tr>
<td class="lorem"></td>
<td></td>
</tr>
</tbody>
</table>
```

Expected output:

```html
<table class="lorem">
<thead>
<tr>
<th>Foo</th>
<th>Baz</th>
</tr>
</thead>
<tbody>
<tr>
<td>sin</td>
<td>cos</td>
</tr>
</tbody>
</table>
```

**Comment by schl3ck** [comment]
I got it to apply the class to the `<table>` element by moving it to a seperate paragraph:
```
| Foo   | Baz   |
| ----- | ----- |
| sin   | cos   |

{.lorem}
```
Looks like markdown-it treats the last line as par of the table even when it doesn't contain any pipes.

**Comment by valtlai** [comment]
Opened PR #114 to update markdown-it to v12 and a test to use a blank line after the table.

**Comment by valtlai** [comment]
@schl3ck You’re right. That new behavior in markdown-it v12 is correct according to [GitHub Flavored Markdown Spec](https://github.github.com/gfm/#example-202).

Opened PR #114 to update markdown-it to v12 and a test to use a blank line after the table.
