### ISSUE TITLE
attrs for code blocks should be on the <pre> not <code>

### ISSUE THREAD

**Issue by bendavis78** [arve0/markdown-it-attrs#116]
``` javascript {.some-class}
    code_goes_here()
    ```
This markdown creates the following html:
```html
<pre>
    <code class="some-class">
        code_goes_here()
    </code>
</pre>
``` 

This makes it impossible to have full control over the style of the code block, since you can't target parent elements based on child selectors. Ideally the output should be:

```html
<pre class="some-class">
    <code>
        code_goes_here()
    </code>
</pre>
```

This is more compatible because we can now target the child code block based on a selector for the parent.

**Comment by arve0** [comment]
Read this paragraph: https://github.com/arve0/markdown-it-attrs#custom-rendering
