### ISSUE TITLE
Link target _blank inside italics does not work in markdown-it-attrs

### ISSUE THREAD

**Issue by kkgthb** [arve0/markdown-it-attrs#124]
This package doesn't gracefully handle `{target="_blank"}` links inside of italics the way, say, Jekyll's Kramdown parser for GitHub Pages sites does.  This is blocking me from migrating old Markdown files from a Jekyll site to 11ty.

**Markdown-it versions:**

* markdown-it@12.0.4
* markdown-it-attrs@4.0.0

**Example input:**

```md
_**P.S.**  See [this link](https://example.com){target="_blank" rel="noopener"} for more info._
```

**Current output:**

```html
<p>_See <a href="https://example.com">this link</a>{target="<em>blank" rel=“noopener”} for more info.</em></p>
```

**Expected output:**

```html
<p><em>See <a href="https://example.com" target="blank" rel="noopener">this link</a> for more info.</em></p>
```

**Comment by arve0** [comment]
Hi 👋 Have you tried `*` instead of `_` for italics?

**Comment by kkgthb** [comment]
Hi @arve0 , I'm aware that `*` is an alternative to `_` for italics in Markdown, but I'm not interested in trying to find-and-replace only the `_` symbols serving as italicizers in 4 years worth of blog post `.md` files that I'm trying to migrate from Jekyll to 11ty.  Not going to happen.

**Comment by arve0** [comment]
Hi again 🙂 I do not believe this is solvable in markdown-it-attrs, as markdown-it-attrs relies on markdown-it to parse the markdown. The rules are, `_` open italics, `_` closes it. markdown-it does not know about the `{}`-curlies rules, which are applied _after_ parsing the markdown.
