### ISSUE TITLE
unable to add attribute on <p> within list

### ISSUE THREAD

**Issue by grant-g** [arve0/markdown-it-attrs#126]
This is an issue template. Fill in your problem description here, replacing this text. Below you should include examples.

Markdown-it versions:
```
% npm ls | grep markdown-it
├─┬ markdown-it@12.0.6
├── markdown-it-attrs@4.0.0
├── markdown-it-deflist@2.1.0
├── markdown-it-footnote@3.0.3
```

Example input:

```md
1. List item normal text.

    List item additional paragraph that wants to have class "tip"
    {: .tip}
```

Current output:

```html
<ol class="tip">
  <li>
    <p>List item normal text.</p>
    <p>List item additional paragraph that wants to have class &quot;tip&quot;</p>
  </li>
</ol>
```

Expected output:

```html
<ol>
  <li>
    <p>List item normal text.</p>
    <p class="tip">List item additional paragraph that wants to have class &quot;tip&quot;</p>
  </li>
</ol>
```

**Comment by cjcarpen** [comment]
This would be really helpful for us

@arve0 any idea when you'd have time to assess whether this is something that can be delivered?

**Comment by arve0** [comment]
Hi! Have you read this section of the documentation, https://github.com/arve0/markdown-it-attrs#ambiguity? Tried without newline?

**Comment by grant-g** [comment]
I've tried without the newline, it causes the second paragraph to be joined to the first one.  And the attribute still ends up on the list element.

**Comment by arve0** [comment]
Could you use html blocks to solve it? 

Sounds like the ambiguity is hard to solve. Some would like it to apply to the li, others the p.

If you would like to avoid html, a span plug-in could be used. Or else, forking this project. 

Curious, what IBM product are you using this in?

**Comment by grant-g** [comment]
The hope was to avoid HTML or other special-casings if possible.

The project is [marked-it](https://github.com/IBM/marked-it). It's been around for a while but until now has used [marked](https://github.com/markedjs/marked) for its md->html generation and [custom-built attributes functionality on top](https://github.com/IBM/marked-it/blob/master/lib/htmlGenerator.js). Switching to use markdown-it + plugins instead is an easier path to maintain going forward.

In our current implementation this case works and is written as:
```
1. List item normal text.

    List item additional paragraph that wants to have class "tip"
    {: .tip}
```

An author wanting the attribute to end up on the list instead would write:
```
1. List item normal text.

    List item additional paragraph that wants to have class "tip"
{: .tip}
```

An author wanting the attribute to end up on the list item instead would write (similar to markdown-it-attrs but at the line beginning rather than the end):
```
1. {: .tip} List item normal text.

    List item additional paragraph that wants to have class "tip"
```

**Comment by arve0** [comment]
I see. At glance, that seems like a breaking change. As I "just" maintain this library, not an active user anymore, I’m not motivated to do such changes. 

If you like, you can hire me to create a fork or configuration option for syntax like that. 

I’m leaving for vacation tomorrow, so will be away from computer the next weeks.

**Comment by grant-g** [comment]
We've made an adaptation for this in our fork.  Since it sounds like it's not a change you're considering for the main repo I'll close the Issue.
