### ISSUE TITLE
Readme 'custom blocks' section outdated?

### ISSUE THREAD

**Issue by tlylt** [arve0/markdown-it-attrs#134]
Hi,

While looking through the code to understand how it does the parsing, I realized that the description in the [Custom-blocks](https://github.com/arve0/markdown-it-attrs#custom-blocks) seems to be outdated.
Quoting it below for reference:
> markdown-it-attrs will add attributes to any token.block == true with {}-curlies in end of token.info. For example, see markdown-it/rules_block/fence.js which stores text after the three backticks in fenced code blocks to token.info.

> Remember to render attributes if you use a custom renderer.

In particular, I think it is no longer the case that `markdown-it-attrs will add attributes to any token.block == true with {}-curlies in end of token.info.`. Now it seems to be more complex than what's described here because of the rewrite with patterns and transforms.

Pointing it out in case there's a need to update it. Thanks!

**Comment by arve0** [comment]
Hi 🙂 I think this still holds, does it not?

> any token.block == true

This part of test: https://github.com/arve0/markdown-it-attrs/blob/master/patterns.js#L26

> with {}-curlies in end of token.info

Test part: https://github.com/arve0/markdown-it-attrs/blob/master/patterns.js#L27

The pattern name is _fenced code blocks_, but it will apply to any token matching the test.

**Comment by tlylt** [comment]
> Hi 🙂 I think this still holds, does it not?
> 
> > any token.block == true
> 
> This part of test: [`master`/patterns.js#L26](https://github.com/arve0/markdown-it-attrs/blob/master/patterns.js?rgh-link-date=2021-12-30T19%3A42%3A12Z#L26)
> 
> > with {}-curlies in end of token.info
> 
> Test part: [`master`/patterns.js#L27](https://github.com/arve0/markdown-it-attrs/blob/master/patterns.js?rgh-link-date=2021-12-30T19%3A42%3A12Z#L27)
> 
> The pattern name is _fenced code blocks_, but it will apply to any token matching the test.

Ah ok, sorry I think I misunderstood it to mean **only** for `token.block == true with {}-curlies in end of token.info`, which is not the case anymore (as long as they match one of the patterns described). I think I was confused because the [link](https://github.com/arve0/markdown-it-attrs/blob/a75102ad571110659ce9545d184aa5658d2b4a06/index.js#L100) below was referencing the file `markdown-it-attrs/index.js` in an old commit. So, I scrolled up and saw the version of the `index.js` without patterns and transforms.
![image](https://user-images.githubusercontent.com/41845017/147803266-7774cfca-98b8-4c28-ba0c-b752b009bff2.png)

Anyways thanks for the clarification!
