### ISSUE TITLE
Allow for use with markdown-it >=13?

### ISSUE THREAD

**Issue by schanzer** [arve0/markdown-it-attrs#139]
The current version of `markdown-it` is disallowed by this package. If there's a compatibility issue, it would be great to see it resolved. And if not, perhaps the fix is as simple as updating the version string in package.json?

**Comment by arve0** [comment]
Hi 👋 Thanks for reporting. Should probably be as easy as updating and running the tests, yes. You want to give it a go?

**Comment by schanzer** [comment]
done!

**Comment by arve0** [comment]
Released in v4.1.4.
