### ISSUE TITLE
Options object for custom types

### ISSUE THREAD

**Issue by felixsanz** [arve0/markdown-it-attrs#15]
Currently, it's impossible to apply attributes to types that are not hardcoded. I tried to implement my self this feature but i think it needs a bit of re-do and i don't fully understand what this plugin does internally :(

My idea is, pass an option object, like this:

```javascript
md.use(MarkdownItAttrs, {
  sample: 'block', // "sample" type, which is a block
  abbr: 'inline', // "abbr" type, which is inline
})
```

This way, we can have inside curlyAttrs() something like this:

```javascript
if (opts) {
  if (opts[tokens[i].type] && hasCurly(tokens[i].info)) {
    // At this point, the token is custom and the type also contains attributes
    // Here we also know if its inline or block, by just checking opts[tokens[i].type]
  }
}
```

But here i don't even know how to continue. Hardcoding the code (copying code from fence block you added lately) will work, but only for block elements and it's not much flexible.

My idea is, re-factoring this into 2 functions, `parseAsInline` and `parseAsBlock`. This two functions will accept the type, and simply return the element with the attributes added correctly. This way you can simply do:

```javascript
if (opts) {
  if (opts[tokens[i].type] && hasCurly(tokens[i].info)) {
    if (opts[tokens[i].type] === 'block') return parseAsBlock(tokens[i], tokens[i].info)
    return parseAsInline(tokens[i], tokens[i].info)
  }
}
```

This of course can be also done with 1 simple function like `parseElement(type, element, attrs)`

> `parseElement(opts[tokens[i].type], tokens[i], tokens[i].info)`

This will make this plug-in fully compatible with other plug-ins that create custom types. I currently have https://github.com/felixsanz/markdown-it-samp, which creates a `<pre><samp>` element (similar to fenced but `samp` instead of `code`).

What do you think of this? I'm sorry that i could not provide a pull request with this implemented, i'm still learning the internals of markdown-it and my implementation will have a lot of bugs...

Thanks

**Comment by arve0** [comment]
> Currently, it's impossible to apply attributes to types that are not hardcoded

That is correct. Current support limits it self to inline elements, lists and code blocks. Current approach have been to look at the token structure to prevent writing a parser, which is kind of limiting.

> i don't fully understand what this plugin does internally

It goes something like this:

1. Let markdown-it parse the markdown.
2. Look at the [token stream](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%60%60%60python%20%7B.red%7D%5Cnfor%20i%20in%20range%2810%29%3A%5Cn%60%60%60%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22debug%22%7D%7D).
3. Add attributes to the tokens.
4. In general, renderer is not affected (exception is [inline code renderer](https://github.com/arve0/markdown-it-attrs/blob/master/index.js#L95))

> But here i don't even know how to continue. 

I can help you in the right direction, but I'm unsure if I'm understanding you correctly. Let me try to summarize:

1. You want custom elements __rendered__.
2. Attributes should be attached to them.

Is that what you want to do?

If so, your work with `markdown-it-samp` seems correct, replacing the renderer. In addition, you should render the attributes in [this line](https://github.com/felixsanz/markdown-it-samp/blob/master/index.js#L96). And that _should_ be it.

I think what you are looking for is [`renderAttrs`](https://markdown-it.github.io/markdown-it/#Renderer.renderAttrs). See [here for an example](https://github.com/arve0/markdown-it-attrs/blob/master/index.js#L100).

**Comment by felixsanz** [comment]
Hehe, actually i don't mean "how i do render attributes in my samp plugin?"

This issue is about making markdown-it-attrs **compatible** with other plugins. My samp plugin is just an example.

The code i pasted above is about passing an options object **INTO** markdown-it-attrs, containing custom types (like my samp one). This way, **your plugin will be able to add attributes** to custom types (plugins like my samp), **not only** to the hardcoded types in your library.

So again, this is about passing to markdown-it-attrs an options object containing strings of custom types.

```javascript
md.use(MarkdownItAttrs, {
  sample: 'block', // "sample" type, which is a block
  abbr: 'inline', // "abbr" type, which is inline
})
```

This code will make markdown-it-attrs **able** to use attributes in custom types/plugins. But the logic needs to be implemented (an example is in my first message).

What you proposed is adding attributes to my plugin manually.
What i propose is  making your plugin able to add attributes to custom elements (plugins), not only core elements like it does right now

**Comment by arve0** [comment]
I'm not following you. Why would you create a parser for `samp` which is fully equivalent to the fenced code block parser? Why not just render fenced code blocks as `samp`?

This plugin works with other plugins which actually look at the `token.attrs`, which currently markdown-it-samp does not.

**Comment by arve0** [comment]
Can you give me an example of what you want to do, in markdown and html?

Like this:

<pre>
```{.red}
text
```
</pre>
to
```html
<pre>
  <samp class="red">text</samp>
</pre>
```

**Comment by felixsanz** [comment]
Your plugin (markdown-it-attrs) only add attributes to hardcoded elements in `index.js`. Right? Like `inline`, `fence`, `paragraph_open`, `bullet_list_open`, etc.

What i'm saying is: How do you add attributes with markdown-it-attrs to **OTHER** aka **CUSTOM** types? It's impossible right?

That's why im propossing the change. You example is wrong because my samp plugin does **not** use backticks **`**. It uses the other ones **´**. So this is not a fenced element, but a **custom** one.

**Comment by felixsanz** [comment]
Example token stream:

```
paragraph_close
list_item_close
bullet_list_close
paragraph_open
inline
paragraph_close
fence
sample     <--- this is my custom element, and markdown-it-attrs can't style it
paragraph_open
inline
paragraph_close
heading_open
inline
heading_close
paragraph_open
inline
```

**Comment by felixsanz** [comment]
And i think i can now answer your questions:

> Why would you create a parser for samp which is fully equivalent to the fenced code block parser? 

Because is not fully equivalent. fenced uses ` and sample uses ´. Those are different opening/closing characters and also generate different output `<code>` vs `<samp>`.

> Why not just render fenced code blocks as samp?

Because i also want to render code elements. If i overwrite the renderer i will not be able to create `<code>` tags anymore.

**Comment by arve0** [comment]
Aha, in that case one need to find a common pattern for the different kind of blocks.

To elaborate: 
- In inline blocks we find the {} curlies in [`tokens[n].children[m].content`](https://github.com/arve0/markdown-it-attrs/blob/master/index.js#L55).
- In fenced code blocks we find the {} curlies in [`tokens[n].info`](https://github.com/arve0/markdown-it-attrs/blob/master/index.js#L15).

What would work right now is if you parse samp fences as:

```
samp_open
inline <-- {} curlies will be found here
samp_close
```

**Comment by arve0** [comment]
Another approach would be to add attrs to any block with 

```js
if (token.info && hasAttrs(token.info)) {
  // add attributes to token
}
```

**Comment by felixsanz** [comment]
> What would work right now is if you parse samp fences as:

> ```
> samp_open
> inline <-- {} curlies will be found here
> samp_close
> ```

but samp is inline itself, **it's not** a block containing inline elements.

> Another approach would be to add attrs to any block with

> ```
> if (token.info && hasAttrs(token.info)) {
>   // add attributes to token
> }
> ```

I like this one. At least working for block elements will save my day and it's easy. Inline elements will be a bit harder i think, but to be honest i don't even need them xD

**Comment by arve0** [comment]
Ok, I'll try it out. 2 sec.

**Comment by felixsanz** [comment]
For block elements, you can change this:

```javascript
      if (tokens[i].type === 'fence' && hasCurly(tokens[i].info)) {
        var codeCurlyStart = tokens[i].info.indexOf('{');
        var codeCurlyEnd = tokens[i].info.indexOf('}');
        var codeAttrs = utils.getAttrs(tokens[i].info, codeCurlyStart + 1, codeCurlyEnd);
        utils.addAttrs(codeAttrs, tokens[i]);
        tokens[i].info = tokens[i].info.substring(0, codeCurlyStart);
        continue;
      }
```

To this:

```javascript
      if (tokens[i].block && hasCurly(tokens[i].info)) {
        var blockCurlyStart = tokens[i].info.indexOf('{');
        var blockCurlyEnd = tokens[i].info.indexOf('}');
        var blockAttrs = utils.getAttrs(tokens[i].info, blockCurlyStart + 1, blockCurlyEnd);
        utils.addAttrs(blockAttrs, tokens[i]);
        tokens[i].info = tokens[i].info.substring(0, blockCurlyStart);
        continue;
      }
```

What do you think?

**Comment by felixsanz** [comment]
Example custom token:

```javascript
Token {
  type: 'sample',
  tag: 'samp',
  attrs: null,
  map: [ 28, 33 ],
  nesting: 0,
  level: 0,
  children: null,
  content: 'test\n',
  markup: '´´´',
  info: ' {.foo}',
  meta: null,
  block: true,
  hidden: false }
```

This should add class="foo" to <samp>

**Comment by arve0** [comment]
I did not restrict it to `token.block === true`, do you think one should?

**Comment by felixsanz** [comment]
If this patch doesn't work for inline elements, it should check `token.block === true`. But i'm not sure of the first.

It will work for inline elements too?

**Comment by arve0** [comment]
Depends on how the inline element renders. Not sure what the use case for *top* inline element with attributes would be. I added the `block` test.

**Comment by arve0** [comment]
Released in v0.5.0.

**Comment by felixsanz** [comment]
```javascript
'use strict';
var assert = require('assert');
var Md = require('markdown-it');
var markdownItAttrs = require('./');
var markdownItSamp = require('markdown-it-samp');
var markdownItMark = require('markdown-it-mark');
var utils = require('./utils.js');

describe('markdown-it-attrs plugins', function() {
  var md;
  beforeEach(function(){
    md = Md().use(markdownItAttrs).use(markdownItSamp).use(markdownItMark);
  });

  it('should support attributes in custom blocks', function(){
    var src = '´´´ {.c a=1 #ii}\nresult\n´´´';
    var expected = '<pre><samp class="c a="1" id="ii">result\n</samp></pre>\n';
    var res = md.render(src);
    assert.equal(res, expected);
  });

  it('should support attributes in custom inline element', function(){
    var src = '==marked=={.c a=1 #ii}';
    var expected = '<p><mark class="c a="1" id="ii">marked</mark></p>';
    var res = md.render(src);
    assert.equal(res, expected);
  });
});
```

```
  20 passing (66ms)
  2 failing

  1) markdown-it-attrs plugins should support attributes in custom blocks:

      AssertionError: '<pre><samp>result\n</samp></pre>\n' == '<pre><samp class="c a="1" id="ii">result\n</samp></pre>\n'
      + expected - actual

      -<pre><samp>result
      +<pre><samp class="c a="1" id="ii">result
       </samp></pre>
      
      at Context.<anonymous> (test.js:173:12)

  2) markdown-it-attrs plugins should support attributes in custom inline element:

      AssertionError: '<p class="c" a="1" id="ii">==marked==</p>\n' == '<p><mark class="c a="1" id="ii">marked</mark></p>'
      + expected - actual

      -<p class="c" a="1" id="ii">==marked==</p>
      +<p><mark class="c a="1" id="ii">marked</mark></p>
      
      at Context.<anonymous> (test.js:180:12)
```

**Comment by arve0** [comment]
Have you updated your samp renderer to render attrs? https://github.com/felixsanz/markdown-it-samp/blob/master/index.js#L96

**Comment by felixsanz** [comment]
Sorry, forgot that. Now it's working perfectly :)

For the marker plugin and others, they should also modify the rendering this way. But all fine!

Do you want me to pull request the test case? It's a plugin so maybe not worth since all plugins are not going to validate the test... kinda pointless but meh :)

**Comment by felixsanz** [comment]
I have curiosity in one thing.

This works perfectly: `<pre><samp class="c" a="1" id="ii">result</samp></pre>`

But what if you want this? `<pre  class="c"><samp a="1" id="ii">result</samp></pre>`

I mean, adding attributes to `<pre>` too. Is that even possible?

(Same case for fenced code blocks `<pre><code>`)

**Comment by arve0** [comment]
> For the marker plugin and others, they should also modify the rendering this way. But all fine!

The mark plugin works fine already, as `==marked=={.red}` is an inline token. As for your test, you are missing a `"`, should be

```js
    var expected = '<p><mark class="c" a="1" id="ii">marked</mark></p>';
```

> Do you want me to pull request the test case?

I think this is the scope of the other plugin. This is tested through the fenced code block.

> But what if you want this? <pre class="c"><samp a="1" id="ii">result</samp></pre>

What in the markdown will differentiate which class goes where? The current {}-curly syntax does not allow this, but [decorate](https://github.com/rstacruz/markdown-it-decorate/) might be able to.

**Comment by felixsanz** [comment]
> What in the markdown will differentiate which class goes where? The current {}-curly syntax does not allow this, but decorate might be able to.

Probably as decorate does:

``` {.classForCode}
code
```
{.classForPre}

I don't like decorate syntax :( But all fine, it was just curiosity, i don't really need to use attributes in `<pre>`. Thanks so much for solving this!

**Comment by arve0** [comment]
Yes, that will be similar to the list syntax, and should be possible. I'll let it hang until someone needs it 🙈

**Comment by felixsanz** [comment]
But since i'm doing:

```javascript
return '<pre><samp' + slf.renderAttrs(token) + '>' + md.utils.escapeHtml(token.content) + '</samp></pre>\n'
```
It will never work, right?

Lists are a special case, because token types are as follow:

```
bullet_list_open
list_item_open
list_item_close
list_item_open
...
bullet_list_close
```

In my case (and in the case of code fences), you only have:

```
fence
```

So how is that going to work?

I think, for it to work, the tokens should be:

```
fence_open
code_open
code_close
fence_close
```

But that is not going to happen, at least with the core code fence block.

:/ So is this even solvable?

**Comment by arve0** [comment]
Just in case you did not know; if you render your attributes to the pre-tag, you can use this CSS-selector to differentiate between the two:

```js
document.querySelector('pre.red > code'); // code element inside pre with class red
document.querySelector('pre.red'); // pre element with class red
```

**Comment by arve0** [comment]
> :/ So is this even solvable?

This structure should work, (wouldn't it?):

```
fence_open
inline type == 'text'
inline type == 'text'
inline type == 'text'
fence_close
```

**Comment by felixsanz** [comment]
But you are unable to create a `<pre class="red">` tag.

    ``` {.red}
    .
    ```

 ```html
<pre><code class="red">.</code></pre>
 ```

**Comment by arve0** [comment]
Overwrite the [renderer](https://github.com/markdown-it/markdown-it/blob/f58e5b16c4b403ee10397f213144ac26c6bd7591/lib/renderer.js#L52-L54):

```js
  return  '<pre' + slf.renderAttrs(token) + '><code>'
        + highlighted
        + '</code></pre>\n';
```

**Comment by felixsanz** [comment]
But now you are unable to apply attributes to `<code>` haha.

In the case of lists you can use attributes in both `<ul>` and `<li>`. Because those are different tokens (bullet_list and list_item)

But in fenced code blocks, you only have ONE token (Check your own [example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%60%60%60js%20%7B.red%7D%5Cnfunction%20%28%29%20%7B%7D%5Cn%60%60%60%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22debug%22%7D%7D))

That only generates 1 token: `"type": "fence",`

So you can only decorate one tag, pre or code, but not both. I'm wrong?

**Comment by arve0** [comment]
You are correct, if considering the current code/state of markdown-it-attrs. But it's not impossible. Just needs to find a common ground where to find the {}-curlies. If they are found with a new line at the end: `\n{.red}`, apply to block, else apply attributes to first inline element. Renderer should take attributes from first inline element and render those to `code`.

**Comment by felixsanz** [comment]
Oh, i see. Well, maybe one day :stuck_out_tongue:
