### ISSUE TITLE
Adding class to last list item

### ISSUE THREAD

**Issue by chaenu** [arve0/markdown-it-attrs#18]
Hey, 

this is possibly related to the fix in https://github.com/arve0/markdown-it-attrs/issues/5

If you add a class to every list item (or just to the last list item) and to the list itself, it adds the right class to all elements except of the last list item. 

Demo:
https://jsfiddle.net/0qkf3kc5/1/

**Comment by arve0** [comment]
Thanks for reporting. Away from computer a couple of days, will look into
it when I'm back.

**Comment by arve0** [comment]
Fixed in `0.6.1`, https://github.com/arve0/markdown-it-attrs/releases/tag/v0.6.1

**Comment by arve0** [comment]
Fixed in `0.6.2`, https://github.com/arve0/markdown-it-attrs/releases/tag/v0.6.2
