### ISSUE TITLE
Forking

### ISSUE THREAD

**Issue by rstacruz** [arve0/markdown-it-attrs#2]
Hey @arve0! I'm hoping to continue a fork of `markdown-it-attrs` with a slightly different goal: style elements using HTML comments instead of text nodes. That is:

```html
> This is a blockquote that's styled.
<!--{.center}-->
```

I've started this over at https://github.com/rstacruz/markdown-it-decorate. Let me know if you're not cool with it, but I really hope you are.

**Comment by arve0** [comment]
Hi @rstacruz !
I'm cool :+1: If you leave me a PR with something like "You might also be interrested in markdown-it-decorate.." in the README.md, I'll approve it.
