### ISSUE TITLE
var char cause issue whith yui compressor

### ISSUE THREAD

**Issue by Psychokrameur** [arve0/markdown-it-attrs#20]
Hello,

in `exports.getAttrs` you have a variable called char.
I didn't dig to understand why but the fact is that when you use YUI compressor on your file, this make him stop with error.
Renaming your variable `character` (or whatever you find suitable) fix this issue.

**Comment by arve0** [comment]
Fixed in `0.6.1`, https://github.com/arve0/markdown-it-attrs/releases/tag/v0.6.1
