### ISSUE TITLE
Use with handlebars

### ISSUE THREAD

**Issue by Psychokrameur** [arve0/markdown-it-attrs#23]
Hello,

I'm using this plugin with Handlebars, with a syntax like "{{....}}", how can I update your plugin to avoid to parse when it starts by '{{' ?

Thanks in advance

**Comment by arve0** [comment]
The syntax is [hard-coded](https://github.com/arve0/markdown-it-attrs/blob/master/index.js#L13), so you will need to look into altering the correct places in [index.js](https://github.com/arve0/markdown-it-attrs/blob/master/index.js). Search for `'{'` and `'}'`.

**Comment by Psychokrameur** [comment]
Thanks, i'll check that.
