### ISSUE TITLE
Change Logs?

### ISSUE THREAD

**Issue by jherdman** [arve0/markdown-it-attrs#24]
Hi! Would it be possible to introduce either a change log or release notes? It's hard to tell what, if anything, has changed, and if I need to take any actions to upgrade my code.

**Comment by arve0** [comment]
Hi! 😄
I try not have any breaking changes, code wise, unless there is a major version bump. Have you experienced otherwise? If so, I'm sorry 😞 

What is of change log now is the [commit log](https://github.com/arve0/markdown-it-attrs/commits/master), but it is a bit thin.

**Comment by jherdman** [comment]
No, there's definitely not been any breakage. Change logs just make it a little faster to determine how much time, and what to suggest to our QA team check when doing regression tests.

**Comment by arve0** [comment]
I'll try to recap the commit log [in github releases](https://github.com/arve0/markdown-it-attrs/releases). OK enough?

**Comment by jherdman** [comment]
This is awesome! Many thanks!
