### ISSUE TITLE
With this plugin enabled, how do I write {} in my document?

### ISSUE THREAD

**Issue by 01AutoMonkey** [arve0/markdown-it-attrs#26]
I need to write {} which in mathematics can refer to an "empty set", but with this plugin enabled it interprets it as an attribute definition and then does nothing with it (since there is no class, id, etc, defined within {}).

Doing `"{}"` works but then I have " and " which I don't want.

Doing `\{}\` works but only the first slash is invisible.

`\{\}` doesn't work.

**Comment by arve0** [comment]
Thanks for the feedback. Could you give me a full example? If I understand you correctly, this currently works:

```js
  it('should do nothing with empty {} curlies', function(){
    var src = 'text with {} curlies';
    var expected = '<p>text with {} curlies</p>\n';

    var res = md.render(src);
    assert.equal(res, expected);
  });
```

**Comment by 01AutoMonkey** [comment]
Ah, it only seems to happen with headers, such as:

`# Nothing 0 〇 ∅ {}`

So I guess that would be:

**Input:** `# Nothing 0 〇 ∅ {}`
**Expected Output:** `<h1>Nothing 0 〇 ∅ {}</h1>`
**Actual Output:** `<h1>Nothing 0 〇 ∅</h1>`

**Comment by arve0** [comment]
Thanks :+1: Should be a easy fix, I'll have a look later today.

**Comment by arve0** [comment]
Hm, I'm unable to reproduce this with current master. Which version are you on (both markdown-it and ..-attrs)?

https://jsfiddle.net/4gatvnt2/

**Comment by 01AutoMonkey** [comment]
I just downloaded the [latest version](https://raw.githubusercontent.com/arve0/markdown-it-attrs/master/markdown-it-attrs.browser.js) and that fixed it.
