### ISSUE TITLE
doesn't work with markdown-it-toc

### ISSUE THREAD

**Issue by KristerV** [arve0/markdown-it-attrs#27]
See details here: https://github.com/samchrisinger/markdown-it-toc/issues/10

**Comment by arve0** [comment]
Thanks for the feedback. Can you attach an example with input and expected output.

**Comment by KristerV** [comment]
good idea, updated the other topic with a minimal example. I don't minf having the conversation here, but makes sense to keep info in one place.

**Comment by arve0** [comment]
`markdown-it-toc` does not render attribues: https://github.com/samchrisinger/markdown-it-toc/blob/master/index.js#L69

Should be done like this: https://github.com/arve0/markdown-it-attrs/blob/a75102ad571110659ce9545d184aa5658d2b4a06/index.js#L100

**Comment by KristerV** [comment]
okay thanks for the tip.
