### ISSUE TITLE
Shorthand for common attributes?

### ISSUE THREAD

**Issue by EricBalingit** [arve0/markdown-it-attrs#30]
If one were to settle on a shorthand convention for common attributes, what would make the most sense?

I'm thinking something like `{@name %data $title}`, and I realize that name and title at least can pose further issues because the rules for those values are loose.

Does this sound practical/worth doing?

**Comment by arve0** [comment]
> If one were to settle on a shorthand convention for common attributes, what would make the most sense?

Using some well known standard or convention would make most sense.

> Does this sound practical/worth doing?

Not for my use case, but it may be worth doing for you? Note that `markdown-it-attrs` add the attributes to the token stream. This means that implementing this syntax should be fairly easy with custom renderers or looping tokens -> fixing attributes which starts with `@`, `%` or `$`. For example, have a look at [markdown-it-for-inline](https://github.com/markdown-it/markdown-it-for-inline) or [the markdown-it plugin docs](https://github.com/markdown-it/markdown-it/tree/master/docs).

**Comment by arve0** [comment]
No response, closing.
