### ISSUE TITLE
Adding dynamic attributes to elements on a page

### ISSUE THREAD

**Issue by julianomoreira** [arve0/markdown-it-attrs#34]
Hello, 

What's the best way to add dynamic IDs to all headings using markdown-it-attrs?

Thanks!

**Comment by arve0** [comment]
Hi,
Can you elaborate what you mean by "dynamic IDs"? An example with input and expected output would be nice too.

**Comment by julianomoreira** [comment]
I need to add IDs to all headings on my page (markdown file) but I don't want to have to enter them manually since we have a lot of pages in markdown. I'd like to generate IDs dynamically on the page so each heading gets a unique ID. Does it make sense? Thanks!

**Comment by arve0** [comment]
Use anchor: https://www.npmjs.com/package/markdown-it-anchor
