### ISSUE TITLE
p inside blockquote gets the class

### ISSUE THREAD

**Issue by lukasoppermann** [arve0/markdown-it-attrs#36]
Hey @arve0,

I really like your packages, it works perfectly. 👍 

I only discovered one little issue: When trying to add a class to a `blockquote` it only adds the class the to `p` inside, but not to the surrounding `blockquote`.

```markdown
> some quote
{.o-column--md-13 .o-column--offset-md-3}
```

I would expect the output to be:

```html
<blockquote class="o-column--md-13 o-column--offset-md-3">
   <p>some quote</p>
</blockquote>
```

However, the actual result is:

```html
<blockquote>
   <p class="o-column--md-13 o-column--offset-md-3">some quote</p>
</blockquote>
```

**Comment by arve0** [comment]
Thanks for reporting. Feel free to poke around to fix it.

**Comment by lukasoppermann** [comment]
Sadly I have no idea at all how to fix it. I looked at the code, but had no idea how it fix it, sorry.

**Comment by arve0** [comment]
Looking at the [parsed tree might help you](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3E%20blockquote%5Cn%7B.class%7D%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22debug%22%7D%7D).

**Comment by oncletom** [comment]
The parsed tree seems to consider the `content` `{.class}` to be located _after_ a softbreak _inside_ the blockquote paragraph, _before_ the `paragraph_close`, _before_ the `blockquote_close`.

Likewise for the `ul/li` example, I guess:

```
> blockquote {.class}
```

would output

```
<blockquote>
  <p class="class">blockquote</p>
</blockquote>
```

whereas:

```
> blockquote
{.class}
```

would output

```
<blockquote class="class">
  <p>blockquote</p>
</blockquote>
```

and finally

```
> blockquote

{.class}
```

would output

```
<blockquote>
  <p>blockquote</p>
</blockquote>

<p class="class"></p>
```

Is that right?

**Comment by arve0** [comment]
Sounds right to me.

**Comment by lukasoppermann** [comment]
Thanks, that solves it. I somehow seem to not have understood that from the readme. I think it was because of the list item example, which I guess works because there it is between content and block element, while my issue was between two block elements?

If so maybe the readme could be enhanced to reflect this difference. Thanks.

**Comment by arve0** [comment]
This is still an issue, reopening.

**Comment by oncletom** [comment]
Thanks @arve0, was not trivial to fix looking at the PR 👍

**Comment by arve0** [comment]
Yes, the code is a mess, and I need to refactor. Support for blockquotes are not published yet, but you can install directly from the repo using [npm install arve0/markdown-it-attrs#master](https://docs.npmjs.com/cli/install).
