### ISSUE TITLE
Remap classes?

### ISSUE THREAD

**Issue by rauschma** [arve0/markdown-it-attrs#37]
Is there a way to remap classes? For example:

```md
## Heading {.foo}
```

Produces the following output (with a mapping `{foo: 'bar'}`

```text
<h1 class="bar">Heading</h1>
```

My use case: I’d like to target different HTML slide frameworks with the same Markdown source. Each of those frameworks uses different CSS classes. Therefore, I’d define my own class names and map them to the class names of the frameworks.

**Comment by arve0** [comment]
Sure, but I'm unsure if it's within the scope of this plugin. You could easily create this with either

1. Modify the token stream after this plugin, changing the class name. 
2. Create a custom renderer. 

You can read more details about this here: https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md

To grasp the token stream, take a look at the debug in markdown-it live demo: https://markdown-it.github.io

**Comment by rauschma** [comment]
True! Thanks for the pointers!
