### ISSUE TITLE
Doesn't work with tables

### ISSUE THREAD

**Issue by cschweda** [arve0/markdown-it-attrs#39]
I can't seem to get this to work with tables.

Is there any way to add a class to a markdown table?

**Comment by arve0** [comment]
Hi, thanks for reporting. 

Tables are not a standard commonmark feature. Van you give a full example, with plugins you use, input and expected output?

**Comment by cschweda** [comment]
Something like this:

|  Header1 | Header2  |
|---|---|
| 3  | 4  |
|   5|  6 |

(Generated via: http://www.tablesgenerator.com/markdown_tables)

Essentially, I just want to insert class attributes (or even just a single attribute) in the <table> tag.
