### ISSUE TITLE
Crashes UglifyJS

### ISSUE THREAD

**Issue by zentuit** [arve0/markdown-it-attrs#43]
We're using the latest package in a project and during the uglify build step, UglifyJS crashes because of index.js. Seems that built index.js still has `let` instead of `var`.

Specifically this line in `index.js` is causing the error:
```
    let tokens = state.tokens;
```

**Comment by zentuit** [comment]
I have a PR coming that seems to work for me. I'd like to see if it works for you.

**Comment by arve0** [comment]
Fixed in `v1.0.1`.

**Comment by zmiKaminski** [comment]
@zentuit I am experiencing this same error as you but with `markdown-it-attrs` 1.0.1 & 1.1.0 using `uglify-js` 3.1.0.  Perhaps you can tell me what version combination is working for you?

**Comment by arve0** [comment]
@zmiKaminski You can use the browser build like this:

```js
let attrs = require('markdown-it-attrs/markdown-it-attrs.browser.js')
```

The browser build does not contain any ES2015.
