### ISSUE TITLE
 second curly braces removed

### ISSUE THREAD

**Issue by aaronh86** [arve0/markdown-it-attrs#58]
Wiki.JS are using your package. I was having issues with the math function and tracked it back to when your package is used and I enter {1}{2}, it removes the second curly braces. 
Is there some way to fix this in your package?
Example input:
```md
{1}{2}
```

Current output:
```html
{1}
```

Expected output:
```html
{1}{2}
```

**Comment by arve0** [comment]
Hi! Thanks for reporting. This sounds like a bug. I will take a look at it when I find some time. In the meantime you can take a look at the code yourself.

**Comment by CalebKester** [comment]
What would the fix for this be? require it to start with `.` or  `#` or contain a `=` so you only capture classes, id's or attributes?

Just wondering as I'm running into a similar issue and my workaround is just `{1}{2}{}`.

**Comment by arve0** [comment]
Attributes are not allowed to start with numbers, so the plugin should correctly detect if what's inside the curlies are actual attributes.

**Comment by arve0** [comment]
I've looked into [the spec of HTML5 attributes](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2), and it is quite permissive. `<p 1>` is actually allowed. This means that there is no way for the plugin to detect the intent of `{1}` vs `{a=1}` based on correctness. Both are allowed attributes.

This is not what you want, so you should do a fork an mold `utils.hasCurly` to fit your use case. For example, adjust `minCurlyLength` here: https://github.com/arve0/markdown-it-attrs/blob/master/utils.js#L140

You can install your own fork with `npm install CalebKester/markdown-it-attrs` (pulls from github master branch).

Hope this helps you 😸

**Comment by arve0** [comment]
As of `v2.1.0` you can configure which delimiters you use.  See [custom delimiter](https://github.com/arve0/markdown-it-attrs#custom-delimiter) in the readme.

**Comment by CalebKester** [comment]
@arve0 any chance you could support delimiters > 1 character? example: `{{{`

**Comment by arve0** [comment]
@CalebKester Tracked in #65
