### ISSUE TITLE
Attributes for code fences

### ISSUE THREAD

**Issue by simondean** [arve0/markdown-it-attrs#59]
I'm trying to use `markdown-it-attrs` with a code fence / code block.  I'm passing a custom `highlight` function to `markdown-it`.  See https://github.com/simondean/markdown-it-issues/blob/master/highlight-attrs/index.js for some example code and https://github.com/simondean/markdown-it-issues/blob/master/highlight-attrs/index.html for the HTML that's produced.  I've also included copies of the markdown and HTML output below.  

It looks `markdown-it-attrs` is injecting attributes into the HTML when I don't use a custom 'highlight' function but as soon as I add the custom `highlight` function, `markdown-it-attrs` is no longer able to inject attributes.  

Looking at the source code in https://github.com/markdown-it/markdown-it/blob/master/lib/renderer.js#L39 the built-in `fence` has functionality that makes it work with an extension like `markdown-it-attrs` (e.g. it has access to the current `token` and can call the `slf.renderAttrs` method but that functionality isn't accessible to a custom `highlight` function.  

Example input:
```md
# Example

```javascript {.some-class}
function helloWorld() {
  return 'Hello, World!';
}
```

# Current output

```html
<h1>Example</h1>
<pre class="highlight tab tab-javascript"><code><span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">helloWorld</span>(<span class="hljs-params"></span>) </span>{
  <span class="hljs-keyword">return</span> <span class="hljs-string">'Hello, World!'</span>;
}
</code></pre>
```

# Expected output

The expected output is the same as the current output, except for the addition of the `some-class` class on the `pre` tag.  

```html
<h1>Example</h1>
<pre class="highlight tab tab-javascript some-class"><code><span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">helloWorld</span>(<span class="hljs-params"></span>) </span>{
  <span class="hljs-keyword">return</span> <span class="hljs-string">'Hello, World!'</span>;
}
</code></pre>
```

**Comment by simondean** [comment]
Having looked into this some more, I don't think this is an issue that the `markdown-it-attrs` module can solve.  I've raised an issue on the `markdown-it` issue tracker.

**Comment by arve0** [comment]
You can create a custom renderer that does the `<pre>`-part (and has access to attributes), then the highlight function should the the inner `<code>`-part.

**Comment by simondean** [comment]
Thanks @arve0 for suggesting a customer renderer.  I've taken that approach in PR https://github.com/Mermade/shins/pull/33
