### ISSUE TITLE
table row attribute

### ISSUE THREAD

**Issue by mhamri** [arve0/markdown-it-attrs#62]
hi, thanks for awesome library.

i'm facing this issue that the library doesn't support row and cell attribute

```
|header1| header2| {.headClass}
|---|---|
|1|2|
|3|4|{.rowClass}
|5|6|
{.tableClass}
```
should result to 
```
<table class="tableClass">
    <thead class="headClass">
        <tr>
            <th>head1</th>
            <th>head2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>2</td>
        </tr>
        <tr class="rowClass">
            <td>3</td>
            <td>4</td>
        </tr>
        <tr>
            <td>5</td>
            <td>6</td>
        </tr>
    </tbody>
</table>
```

at the moment only the table class is supported. but I think it will be awesome if we can also apply attr on row level

**Comment by arve0** [comment]
PRs welcome :octocat:

**Comment by arve0** [comment]
I'll close this issue, as I'm not going to implement it myself. If anyone wants to implement, feel free to reopen issue.
