### ISSUE TITLE
markdown-it-highlight lines conflict

### ISSUE THREAD

**Issue by hipstersmoothie** [arve0/markdown-it-attrs#63]
I am using this with markdown-it-highlight lines. I transform everything into jsx for my app. When writing:

````
```js{2}
```
````

this plugin adds `2=""` to the code element. Which is invalid html and causes errors. 

Is there any way to turn off this plugin for code blocks? Or an option to configure the `{}` characters? If I could change them to `[]` I think everything would work.

**Comment by hipstersmoothie** [comment]
I can do the '{' configuration if no one want to! 👍

**Comment by arve0** [comment]
Hi! This is related to #58, see [comment in 58](https://github.com/arve0/markdown-it-attrs/issues/58#issuecomment-386858002).

**Comment by arve0** [comment]
Yes, I would. Nice if the `.use` API handles with/without options:

```js
// current
md.use(attrs)
// new
md.use(attrs({
  leftDelimiter: '[',
  rightDelimiter: ']'
})
```
