### ISSUE TITLE
Bower Package?

### ISSUE THREAD

**Issue by jherdman** [arve0/markdown-it-attrs#7]
Would it be possible to make this plugin available to Bower as well? Ideally as an AMD package.

**Comment by arve0** [comment]
Hi!
I'm not familiar with AMD. What about using a *your tech* as a service? For example https://wzrd.in

**Comment by jherdman** [comment]
Ideally I'd prefer to host the JavaScript myself. It looks to me like other authors are using browserify to prepare a compatible version of the package: https://github.com/markdown-it/markdown-it-emoji/blob/4d5f6af1b6efb0975dae2ac51dbe6252636724aa/Makefile#L26-L44. I can look into this if there's appetite to support this in the build process.

**Comment by arve0** [comment]
Yes, `browserify index.js --standalone -o markdown-it-attrs.js` should do it. Seems like [it should work with AMD too](https://github.com/substack/browserify-handbook#standalone).

**Comment by arve0** [comment]
Assuming you use npm, you can now copy markdown-it-attrs.browser.js into your build and host the code yourself. I'm unsure if you should use `markdown-it-attrs` when requiring with AMD, or `markdownItAttrs`. Let me know what you find out.

**Comment by jherdman** [comment]
Worked like a charm! I'll be opening a PR shortly to add a bower.json file.

I'm using this in an Ember project, so, aside from installing this as a bower component I needed a vendor shim, which makes AMD sort of behave like ES6 modules.
