### ISSUE TITLE
Available attributes whitelist

### ISSUE THREAD

**Issue by jrchudy** [arve0/markdown-it-attrs#73]
Do you intend to add support to the library so that a whitelist of allowed attributes can be defined for the tool? 

I would like to limit users from defining `on-load` and other script style attributes, and found that it would be easier to only allow the set that we know of that the users want instead of trying to search for the full set that we don't want them to use.

**Comment by arve0** [comment]
> Do you intend to add support to the library so that a whitelist of allowed attributes can be defined for the tool?

Not at the moment. I feel this a match for a stand-alone plug-in, as there is other ways to sneak in insecurities.

**Comment by jrchudy** [comment]
> there is other ways to sneak in insecurities.

Do you care to elaborate more on those other concerns? The whitelist was the one way I could think of to remove most security concerns but I didn't notice anything else that may be of concern.

**Comment by arve0** [comment]
From the top of my head:

1. Enabling HTML in markdown-it.
2. Other plugins.
3. Bugs.

It would be better to have a whitelist plugin, that catches all of these entries.

**Comment by arve0** [comment]
Closing, many solutions for whitelisting HTML are available, for example https://www.npmjs.com/package/sanitize-html.

**Comment by arve0** [comment]
Fixed in #84
