### ISSUE TITLE
how to escape {...} as plain text?

### ISSUE THREAD

**Issue by naivefun** [arve0/markdown-it-attrs#77]
It seems everything between {...} is parsed as attributes. So how can I render plain text like 'Text = {a  b}' ?

This is only rendered as `Text =` now.

**Comment by arve0** [comment]
https://github.com/arve0/markdown-it-attrs#custom-delimiters

**Comment by rlidwka** [comment]
You can escape it with backslash like this `Text = \{a b}` starting from markdown v13 (commit https://github.com/markdown-it/markdown-it/commit/75037c6514e99c9b4fa300f62f04913fee4ea0e2).

*escapes are now put in a separate token which gets merged at the end of core chain, I think it'll work with this plugin with no changes*

ref https://github.com/markdown-it/markdown-it/issues/840
