### ISSUE TITLE
Adding classes to <pre> in fenced code blocks

### ISSUE THREAD

**Issue by disklosr** [arve0/markdown-it-attrs#86]
Current implementation adds attributes to `code` element  in code fences. Is it possible to also add it to `pre` element? I'm trying to use code-highlight plugin for prismjs and it expects a certain attribute -- containing the line numbers to highlight -- to be set in `pre` element.

Any workaround for this?

**Comment by arve0** [comment]
Hi! You can create a custom renderer that print attributes to the <pre>-part. Here is an example (inline code, but same principle): https://github.com/arve0/markdown-it-attrs/blob/a75102ad571110659ce9545d184aa5658d2b4a06/index.js#L95

**Comment by arve0** [comment]
Hi! You can use a custom tenderer to print fences thae way you want them. Here is an example for inline code blocks, which is same in principle: https://github.com/arve0/markdown-it-attrs/blob/a75102ad571110659ce9545d184aa5658d2b4a06/index.js#L95

**Comment by arve0** [comment]
I've created an example in the README: https://github.com/arve0/markdown-it-attrs#custom-rendering

**Comment by disklosr** [comment]
Thanks for the help!
